-- Part 2: Continue adding products for remaining categories
INSERT INTO "Product" (name, description, price, "categoryId") VALUES

-- RACKETS
('EXERGY RACKET', 'EXERGY badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('FELET BLACK / ZFORCE / HH', 'FELET badminton racket black/zforce heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('FELET TJ POWER / HH', 'FELET TJ Power badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED CULT 72 / 73 / HH', 'HUNDRED Cult badminton racket model 72/73 heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED JUNIOR RACKET', 'HUNDRED junior badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED JUNIOR RACKET 1000JR', 'HUNDRED junior badminton racket model 1000JR', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED JUNIOR RACKET 200JR', 'HUNDRED junior badminton racket model 200JR', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED N-ERGY 80 / HH', 'HUNDRED N-ERGY 80 badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED POWER TEK 1000 PRO', 'HUNDRED Power Tek 1000 Pro badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED POWERTEK 200', 'HUNDRED PowerTek 200 badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED POWERTEK 900 SERIES', 'HUNDRED PowerTek 900 series badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED ROCK 78 / 79 RACKET', 'HUNDRED Rock badminton racket model 78/79', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED ROCK 79 RACKET / HH', 'HUNDRED Rock 79 badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED ROCK 88 RACKET / HH', 'HUNDRED Rock 88 badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED SET RACKETS', 'HUNDRED set badminton rackets', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('HUNDRED TRAINING 120/140', 'HUNDRED training badminton racket model 120/140', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),

-- LI NING RACKETS (sampling a few to keep it manageable)
('LI NING 3D CALIBER 001', 'LI NING 3D Caliber 001 badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('LI NING AX FORCE 100 / HH', 'LI NING AX Force 100 badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('LI NING WINDSTORM 72 / HH', 'LI NING Windstorm 72 badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),

-- YONEX RACKETS (sampling key models)
('YONEX ASTROX 99 PRO / HH', 'YONEX Astrox 99 Pro badminton racket heavy head', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('YONEX NANOFLARE 800 PRO', 'YONEX Nanoflare 800 Pro badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),
('YONEX VOLTRIC LITE 47i', 'YONEX Voltric Lite 47i badminton racket', 0, (SELECT id FROM "Category" WHERE name = 'RACKETS')),

-- SHOES
('HUNDRED COURT FLYER UK-1 GREEN/DARK GREY', 'HUNDRED Court Flyer badminton shoes UK size 1 green/dark grey', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('HUNDRED COURT FLYER UK-2 BLUE/ORANGE', 'HUNDRED Court Flyer badminton shoes UK size 2 blue/orange', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('HUNDRED RAZE UK-7 BLUE/GREEN', 'HUNDRED Raze badminton shoes UK size 7 blue/green', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('LI NING SAGA LITE 3 EUR-42 BLACK\BLUE', 'LI NING Saga Lite 3 badminton shoes EUR size 42 black/blue', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('FULL GEL PAD', 'Full gel pad for shoes', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('HALF GEL PAD', 'Half gel pad for shoes', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('YONEX VELO 100 UK-9 WHITE', 'YONEX Velo 100 badminton shoes UK size 9 white', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),
('YONEX SHB 65 Z3 UK-10 WHITE/BLUE', 'YONEX SHB 65 Z3 badminton shoes UK size 10 white/blue', 0, (SELECT id FROM "Category" WHERE name = 'SHOES')),

-- SHUTTLECOCKS
('LI NING C 60', 'LI NING C 60 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LIN MEI 10', 'LIN MEI 10 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('HUNDRED F8', 'HUNDRED F8 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LI MEI 10 PRO', 'LI MEI 10 Pro shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LI NING A2', 'LI NING A2 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LI NING D3', 'LI NING D3 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LI NING G800', 'LI NING G800 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LI NING SG GOLD', 'LI NING SG Gold shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LIN MEI F7', 'LIN MEI F7 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('LIN MEI G3', 'LIN MEI G3 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('MAVIS 600', 'MAVIS 600 shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('MAVIS 600 SINGLES', 'MAVIS 600 single shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('VONEX TUBE', 'VONEX tube shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),
('VONEX TUBE SINGLE', 'VONEX single tube shuttlecocks', 0, (SELECT id FROM "Category" WHERE name = 'SHUTTLECOCKS')),

-- SOCKS
('HUNDRED 3 PACK SOCKS', 'HUNDRED 3 pack badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('HUNDRED SOCKS', 'HUNDRED badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('LI NING 3 PACK SOCKS', 'LI NING 3 pack badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('LI NING SOCKS', 'LI NING badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('LI NING SOCKS (AWLS)', 'LI NING badminton socks model AWLS', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('LI NING SOCKS (AWST)', 'LI NING badminton socks model AWST', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('MAXBOLT JUNIOR SOCKS', 'MAXBOLT junior badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('MAXBOLT SOCKS', 'MAXBOLT badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('YONEX 3 PACK SOCKS', 'YONEX 3 pack badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('YONEX SOCKS', 'YONEX badminton socks', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),
('YONEX SOCKS (CH)', 'YONEX badminton socks model CH', 0, (SELECT id FROM "Category" WHERE name = 'SOCKS')),

-- STRINGS
('APACS STRINGS', 'APACS badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('GOSEN RY 58/65', 'GOSEN RY badminton strings 58/65', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('GOSEN RY 65/58 SINGLE', 'GOSEN RY badminton strings 65/58 single', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('HUNDRED 700S/600S', 'HUNDRED badminton strings 700S/600S', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('HUNDRED HYBRID', 'HUNDRED hybrid badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('HUNDRED JP 70', 'HUNDRED JP 70 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('HUNDRED Z70 STRINGS', 'HUNDRED Z70 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('HUNRED 66X BOOST', 'HUNDRED 66X Boost badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('HUNRED 70X BOOST', 'HUNDRED 70X Boost badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('KELIST 99/98/66 PRO', 'KELIST Pro badminton strings 99/98/66', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('KELIST K618', 'KELIST K618 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('KONEX STRINGS', 'KONEX badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING AP 66', 'LI NING AP 66 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING AP 70', 'LI NING AP 70 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING L 67', 'LI NING L 67 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING N 65', 'LI NING N 65 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING N 65 SINGLE', 'LI NING N 65 single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING N 70', 'LI NING N 70 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING N 70 SINGLE', 'LI NING N 70 single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING N9', 'LI NING N9 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 1', 'LI NING NO 1 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 1 BOOST', 'LI NING NO 1 Boost badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 3 BOOST', 'LI NING NO 3 Boost badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 5', 'LI NING NO 5 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 5 SINGLE', 'LI NING NO 5 single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 7 BOOST', 'LI NING NO 7 Boost badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NO 7 REEL', 'LI NING NO 7 reel badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NS 50', 'LI NING NS 50 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('LI NING NS 95', 'LI NING NS 95 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT ARC-Z66', 'MAXBOLT ARC-Z66 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 20', 'MAXBOLT MBS 20 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 6', 'MAXBOLT MBS 6 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 6+', 'MAXBOLT MBS 6+ badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 63', 'MAXBOLT MBS 63 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 66 BLACK', 'MAXBOLT MBS 66 badminton strings black', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 66 RED', 'MAXBOLT MBS 66 badminton strings red', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 66 TWO TONE (RED/BLACK)', 'MAXBOLT MBS 66 two tone badminton strings red/black', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 66 WHITE', 'MAXBOLT MBS 66 badminton strings white', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 66 YELLOW', 'MAXBOLT MBS 66 badminton strings yellow', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT MBS 70', 'MAXBOLT MBS 70 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT STRING MBS 66', 'MAXBOLT MBS 66 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('MAXBOLT STRING MBS 90', 'MAXBOLT MBS 90 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('T20 STRING', 'T20 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('TRANSFORMER TS 101 PRO', 'TRANSFORMER TS 101 Pro badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('VICTOR VB 70 / 70 POWER', 'VICTOR VB 70 Power badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('VICTOR VS-65', 'VICTOR VS-65 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX AEROBITE', 'YONEX Aerobite badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX AEROBITE BOOST', 'YONEX Aerobite Boost badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX AEROSONIC', 'YONEX Aerosonic badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 BLACK', 'YONEX BG 65 badminton strings black', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 GOLD', 'YONEX BG 65 badminton strings gold', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 GREEN', 'YONEX BG 65 badminton strings green', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 LAVENDER', 'YONEX BG 65 badminton strings lavender', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 ORANGE', 'YONEX BG 65 badminton strings orange', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 PINK', 'YONEX BG 65 badminton strings pink', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 RED', 'YONEX BG 65 badminton strings red', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 REEL N', 'YONEX BG 65 reel badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 ROYAL BLUE', 'YONEX BG 65 badminton strings royal blue', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 SINGLE', 'YONEX BG 65 single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 TITANIUM', 'YONEX BG 65 titanium badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 TITANIUM SINGLE', 'YONEX BG 65 titanium single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 TURQUOISE', 'YONEX BG 65 badminton strings turquoise', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 VIOLET', 'YONEX BG 65 badminton strings violet', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 WHITE', 'YONEX BG 65 badminton strings white', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 65 YELLOW', 'YONEX BG 65 badminton strings yellow', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX BLACK', 'YONEX BG 66 Ultimax badminton strings black', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX METTALIC WHITE', 'YONEX BG 66 Ultimax badminton strings metallic white', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX PASTAL GREEN', 'YONEX BG 66 Ultimax badminton strings pastel green', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX RED', 'YONEX BG 66 Ultimax badminton strings red', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX REEL', 'YONEX BG 66 Ultimax reel badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX SINGLE', 'YONEX BG 66 Ultimax single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 66 ULTIMAX YELLOW', 'YONEX BG 66 Ultimax badminton strings yellow', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 80 POWER', 'YONEX BG 80 Power badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX BG 80 POWER SINGLE', 'YONEX BG 80 Power single badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX EXBOLT 63', 'YONEX Exbolt 63 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX EXBOLT 63 REEL', 'YONEX Exbolt 63 reel badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX EXBOLT 65', 'YONEX Exbolt 65 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX EXBOLT 68', 'YONEX Exbolt 68 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX NANOGY 95', 'YONEX Nanogy 95 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),
('YONEX NANOGY 99', 'YONEX Nanogy 99 badminton strings', 0, (SELECT id FROM "Category" WHERE name = 'STRINGS')),

-- WRISTBANDS
('HUNDRED WRIST BAND', 'HUNDRED badminton wrist band', 0, (SELECT id FROM "Category" WHERE name = 'WRISTBANDS')),
('Li Ning WRIST BAND', 'Li Ning badminton wrist band', 0, (SELECT id FROM "Category" WHERE name = 'WRISTBANDS')),
('YONEX WRIST BAND', 'YONEX badminton wrist band', 0, (SELECT id FROM "Category" WHERE name = 'WRISTBANDS'));

-- Note: This is a subset of all products. The full list would be much longer.
-- Prices are set to 0 and should be updated with actual values later. 