const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

// Current counts from database
const currentCounts = {
  'BAGS': 62,
  'CLOTHS': 7,  
  'GRIPS': 22,
  'NETS': 2,
  'OTHER': 15,
  'RACKETS': 94,
  'SHOES': 133,
  'SHUTTLECOCKS': 8,
  'SOCKS': 7,
  'STRINGS': 61,
  'WRISTBANDS': 2
};

// Complete product dataset from user
const completeProductData = `BAGS	YONEX BOX TYPE (22931 WT)
BAGS	HUNDRED 3 ZIPPER LEVEL-UP BAG (2M145/144)
BAGS	HUNDRED 4M260/4M261
BAGS	HUNDRED 4M260/4M261 BLUE
BAGS	HUNDRED 4M260/4M261 RED
BAGS	HUNDRED 4M260/4M261 YELLOW
BAGS	HUNDRED BACKPACK 3M007
BAGS	HUNDRED BOX TYPE - 3M121
BAGS	HUNDRED BOX TYPE - 3M121 BLACK
BAGS	HUNDRED BOX TYPE - 3M121 BLUE
BAGS	HUNDRED BOX TYPE 2 POCKET - 3M120
BAGS	HUNDRED BOX TYPE 2 POCKET - 3M120 BLACK
BAGS	HUNDRED BOX TYPE 2 POCKET - 3M120 WHITE
BAGS	HUNDRED BOX TYPE 3M009-1
BAGS	HUNDRED COSMO RACKET BAG- 3M085
BAGS	HUNDRED COSMO RACKET BAG- 3M085 BLACK/ASH
BAGS	HUNDRED COSMO RACKET BAG- 3M085 BLACK/RED
BAGS	HUNDRED COSMO RACKET BAG- 3M085 BLUE/BLACK
BAGS	HUNDRED COSMO RACKET BAG- 3M085 BLUE/GOLD
BAGS	HUNDRED IDEAL BAG - 2M148/147/146
BAGS	HUNDRED NUCLEAR EDGE BAG 2M090
BAGS	HUNDRED URBAN POD BAG - 3M152
BAGS	LI NING 2 ZIPPER BLACK -  ABDS681-1
BAGS	LI NING 2 ZIPPER BLUE -  ABDT359-3
BAGS	LI NING 2 ZIPPER BLUE/GREEN -  ABDS681-2
BAGS	LI NING 2 ZIPPER RED -  ABDS681-5
BAGS	LI NING 2 ZIPPER WHITE -  ABDS681-4
BAGS	LI NING 3 POCKET BAG(661/853)
BAGS	LI NING 3 ZIPPER BAG (837/365/687)
BAGS	LI NING BACK PACK ABSU385
BAGS	LI NING BAG ABDU309
BAGS	LI NING BAG ABDU313
BAGS	LI NING BAG ABJS059
BAGS	LI NING BAG ABJU013
BAGS	LI NING BAG ABJU033
BAGS	LI NING BAG ABLU069
BAGS	LI NING BAG ABLV029
BAGS	LI NING BAG LU067
BAGS	LI NING BOX BAG 397 BLACK
BAGS	LI NING BOX BAG 399
BAGS	LI NING MAXIMUS 667/647
BAGS	LI NING SHOE BAG (285)
BAGS	MAXBOLT BOX 4013 BAG
BAGS	YONEX  BACKPACK ACE 2312
BAGS	YONEX 2 ZIPPER BAG (BT6)
BAGS	YONEX 3 ZIP PRO PERFORM BAG - 92429EX
BAGS	YONEX 3 ZIPPER (BT 9)
BAGS	YONEX 3D B1 ZIPPER BOX TYPE BAG
BAGS	YONEX 3D BOX TYPE BAG (3D-2231)
BAGS	YONEX ACE 2326 BAG
BAGS	YONEX BAG 2331WEX
BAGS	YONEX BASIC KITBAG BLACK GRAY
BAGS	YONEX BASIC KITBAG BLACK GRAY YELLOW
BAGS	YONEX BASIC KITBAG NAVY BLUE CYBER LIME
BAGS	YONEX BASIC KITBAG RED BLACK
BAGS	YONEX BASIC KITBAG ROYAL BLUE BLACK
BAGS	YONEX BOX TOURNAMENT BAG 2331
BAGS	YONEX CLUB BACK PACK (22412S)
BAGS	3D 3 ZIPPER  TOURNAMENT BAG
BAGS	APACS 2 ZIPPER BAG
BAGS	LI NING 2 ZIPPER BAG (361/403/359/677/681/839/841)
BAGS	LI NING 2 ZIPPER BAG (SIN)
BAGS	LI NING BACK PACK (BLUE) 269
BAGS	LI NING BACKPACK (IND)
BAGS	LI NING BAG 315
BAGS	LI NING BOX TYPE BAG (363)
BAGS	LIN NING BOX TYPE (319)
BAGS	LIN NING BOX TYPE CRUZE
BAGS	MAXBOLT 1 ZIPPER BAG
BAGS	MAXBOLT 2 ZIPPER BAG
BAGS	VSE RACKET BAG
BAGS	YONEX 2 ZIPPER PERFORMANCE BAG
BAGS	YONEX 3 ZIPPER PERFORMANCE BAG (BA922229EX)
BAGS	YONEX 3D 2 ZIPPER GR 1
BAGS	YONEX 3D 2 ZIPPER GR 2
BAGS	YONEX 3D PERFORMANCE BOX TYPE (22931WT)
BAGS	YONEX BACK PACK (GREEN)
BAGS	YONEX BASIC KITBAG 2215 / 2225/ 23015 / 24015
BAGS	YONEX BOX  BAG 22831
BAGS	YONEX EVOLVING BACK PACK (BLACK)
BAGS	YONEX EXPERT BAG - 2326EX
BAGS	YONEX LEAGE BACK PACK
CLOTHS	HUNDRED SHORTS (3M130/131)
CLOTHS	HUNDRED SHORTS (4M016/017)
CLOTHS	HUNDRED T.SHIRTS (3M123/124/125/126/127/129)
CLOTHS	LI NING / YONEX  T SHIRT (963/707/995/993)
CLOTHS	LI NING / YONEX SHORTS(725/727/745/723)
CLOTHS	LI NING BOTTOM
CLOTHS	LI NING TOP
CLOTHS	ADDIDAS BODY ARMOUR
CLOTHS	BADMINTON SHORTS(DBI)
CLOTHS	BADMINTON T SHIRT
CLOTHS	BADMINTON T SHIRT (CHN)
CLOTHS	BADMINTON T SHIRTS(DBI)
CLOTHS	BADMINTON T-SHIRTS (SA)
CLOTHS	DRY FIT SKINNIES
CLOTHS	DRY FIT T SHIRTS
CLOTHS	LADIES TIGHT LEGGINGS
CLOTHS	LI NING POLO T.SHIRT (691)
CLOTHS	LI NING POLO T.SHIRT (997)
CLOTHS	LI NING T SHIRT (IND)
CLOTHS	LI NING TRACK PANT
CLOTHS	LI NING V NECK T.SHIRT (701)
CLOTHS	MAXBOLT SHORTS
CLOTHS	MAXBOLT T SHIRTS
CLOTHS	OLD LI NING T SHIRT WITH COLOR
CLOTHS	OLD ORIGINAL T - SHIRTS
CLOTHS	ORIGINAL SHORTS
CLOTHS	VSE SKIRTS
CLOTHS	YONEX SHORTS (CHN)
CLOTHS	YONEX SHORTS (MLSYA)
CLOTHS	YONEX T SHIRTS
GRIPS	FELET GRIP
GRIPS	HUNDRED GRIP - GTO 20
GRIPS	HUNDRED GRIP - GTR 17/18/19/34
GRIPS	KONEX TOWEL GRIP
GRIPS	LI NING  GP 20
GRIPS	LI NING  GP 24
GRIPS	LI NING CUSHION WRAP SINGLE
GRIPS	LI NING GP 16/17/18/19
GRIPS	LI NING GP 2000
GRIPS	LI NING TOWEL GRIP (L)
GRIPS	LI NING TOWEL GRIP (S)
GRIPS	LI NING TOWEL GRIP ROLL (GC-200R)
GRIPS	LI NING TOWEL GRIPS(GC 001)
GRIPS	MAXBOLT PU GRIP
GRIPS	MAXBOLT TOWEL GRIP ROLL
GRIPS	MAXBOLT TOWEL GRIP SINGLE
GRIPS	OQO OVER GRIP
GRIPS	SPACESHIP OVER GRIP
GRIPS	YONEX SUPER GRAP OVER GRIP
GRIPS	YONEX TOWEL GRIPS
GRIPS	GOSEN OVER GRIP
GRIPS	GOSEN REPLACMENT GRIP
GRIPS	HUNDRED GRIPS - GTD 25
OTHER	OUT GUTING
OTHER	LI NING K-TAPE BOX
OTHER	APACS GRIP POWDER
OTHER	BADMINTON KEY TAG
OTHER	GOLD KEY TAG
OTHER	GROMMET BOX
OTHER	HUNDRED INSOLE
OTHER	HUNDRED INSOLE PRO
OTHER	IODEX RAPID SPARAY
OTHER	LI NING FLIP-FLOPS
OTHER	LI NING INSOLE
OTHER	LI NING MASK
OTHER	LI NING SKIPPING ROPE (SP333)
OTHER	LI NING SKIPPING ROPE (SP421)
OTHER	LI NING SKIPPING ROPE 776/778
OTHER	LI NING SLIPPERS
OTHER	LI NING TOWEL (L)
OTHER	LI NING TOWEL (S)
OTHER	LI NING TOWEL (YY216)
OTHER	LI NING WATER BOTTLE
OTHER	LI-NING KEY TAG
OTHER	Li-Ning Skipping Rope
OTHER	SHUTTLE KEY TAG
OTHER	SILVER KEY TAG
OTHER	STAY SAFE ICE COLD SPRAY
OTHER	YONEX KEY TAG
OTHER	YONEX WATER BOTTLE
OTHER	DUNLOP SQUASH BALLS
OTHER	LI NING FLASK (RED)
OTHER	MIRRORS
OTHER	OTHER
OTHER	YONEX ANKLE SUPPORT
OTHER	YONEX KNEE SUPPORT
OTHER	FORM ROLLER
OTHER	YOGA MAT (8MM)
NETS	HUNDRED BADMINTON NET BNT-80
NETS	LI NING BADMINTON NET BN450L
NETS	LI NING BADMINTON NET BN600L
NETS	YONEX BADMINTON NET (AC152EX/139A)
NETS	YONEX BN-152 PRO HQ NET
NETS	YONEX BN139R NET
NETS	YONEX HIGH QUALITY NET
RACKETS	EXERGY RACKET
RACKETS	FELET BLACK / ZFORCE / HH
RACKETS	FELET TJ POWER / HH
RACKETS	HUNDRED CULT 72 / 73 / HH
RACKETS	HUNDRED JUNIOR RACKET
RACKETS	HUNDRED JUNIOR RACKET 1000JR
RACKETS	HUNDRED JUNIOR RACKET 200JR
RACKETS	HUNDRED N-ERGY 80 / HH
RACKETS	HUNDRED POWER TEK 1000 PRO
RACKETS	HUNDRED POWERTEK 200
RACKETS	HUNDRED POWERTEK 900 SERIES
RACKETS	HUNDRED ROCK 78 / 79 RACKET
RACKETS	HUNDRED ROCK 79 RACKET / HH
RACKETS	HUNDRED ROCK 88 RACKET / HH
RACKETS	HUNDRED SET RACKETS
RACKETS	HUNDRED TRAINING 120/140
RACKETS	LI NING 3D CALIBER 001
RACKETS	LI NING 3D CALIBER 300 I / B
RACKETS	LI NING 3D CALIBER 500
RACKETS	LI NING 3D CALIBER 500 PRO
RACKETS	LI NING 3D CALIBER 600 I / B
RACKETS	LI NING 3D CALIBER 900B
RACKETS	LI NING 3D CALIBER 900I
RACKETS	LI NING 3D CALIBER X BOOST / HH
RACKETS	LI NING AERONAUT 9000
RACKETS	LI NING ARMOUR 252/232 / EB
RACKETS	LI NING AX FORCE 10 / HH
RACKETS	LI NING AX FORCE 100 / HH
RACKETS	LI NING AX FORCE 20
RACKETS	LI NING AX FORCE 40
RACKETS	LI NING AX FORCE 50
RACKETS	LI NING AX FORCE 60
RACKETS	LI NING AX FORCE 70
RACKETS	LI NING AX FORCE 80
RACKETS	LI NING AX FORCE 90 / HH
RACKETS	LI NING AX FORCE BIG BANG
RACKETS	LI NING AX FORCE BLAST
RACKETS	LI NING AX FORCE CANNON / HH
RACKETS	LI NING AX FORCE CANNON PRO
RACKETS	LI NING BLACKIRON / HH
RACKETS	LI NING BLADE X 500
RACKETS	LI NING BLADE X 73
RACKETS	LI NING BLADE X 900
RACKETS	LI NING BLADE X SONOR
RACKETS	LI NING BLADEX SPIRAL
RACKETS	LI NING G FORCE SUPERLITE MAX 9 / HH
RACKETS	LI NING G FORCE X-5
RACKETS	LI NING GOLD MEDAL RACKET
RACKETS	LI NING HALBERTEC 2000
RACKETS	LI NING HALBERTEC 5000
RACKETS	LI NING HALBERTEC 8000
RACKETS	LI NING HALBERTEC 9000
RACKETS	LI NING HALBERTEC MOTOR
RACKETS	LI NING HIGH CARBON 1000
RACKETS	LI NING SUPERLITE MAX 10 / HH
RACKETS	LI NING TECTONIC 1 / HH
RACKETS	LI NING TECTONIC 3R
RACKETS	LI NING TECTONIC 6
RACKETS	LI NING TECTONIC 7
RACKETS	LI NING TECTONIC 9 4U
RACKETS	LI NING TURBO CHARGING Z BOOST / HH
RACKETS	LI NING TURBO CHARGING Z DRIVE/ HH
RACKETS	LI NING TURBOCHARGING MARSHAL
RACKETS	LI NING WIND LITE SERIES
RACKETS	LI NING WINDSTORM 700 SP
RACKETS	LI NING WINDSTORM 72 / HH
RACKETS	LI NING WINDSTORM 74
RACKETS	LI NING WINDSTORM 75
RACKETS	LI NING WINDSTORM 78S / HH
RACKETS	LI NING WINDSTORM 79 / HH
RACKETS	LI NING WINDSTORM NANO 790 LITE
RACKETS	LI NING XIPHOS X-1
RACKETS	MAXBOLT (BLACK / PEARL) FORCE II (MYS) / HH
RACKETS	MAXBOLT ASSASIN / HH
RACKETS	MAXBOLT ATTROID 3
RACKETS	MAXBOLT BLACK (MYS)
RACKETS	MAXBOLT BLADE
RACKETS	MAXBOLT BLUEFLARE (MYS) / EB
RACKETS	MAXBOLT BOLT 8 / HH
RACKETS	MAXBOLT EXTREME 8 / EB
RACKETS	MAXBOLT FORCE VX / EB
RACKETS	MAXBOLT GALLANT FORCE
RACKETS	MAXBOLT GALLANT SPEED (MYS) / HL
RACKETS	MAXBOLT GALLANT TOUR / HH
RACKETS	MAXBOLT METAL (MYS) / EB
RACKETS	MAXBOLT MINI RACKETS
RACKETS	MAXBOLT NANO TECH 10/11
RACKETS	MAXBOLT NAVIGATOR II / HH
RACKETS	MAXBOLT NEW TENO 12
RACKETS	MAXBOLT NEZER / HH
RACKETS	MAXBOLT PREDATOR(MYS)
RACKETS	MAXBOLT RACKET 180G
RACKETS	MAXBOLT RACKET 9JR BLUE
RACKETS	MAXBOLT RACKET 9JR RED
RACKETS	MAXBOLT RACKET BLACK WOVEN LTD / HH
RACKETS	MAXBOLT RACKET COVER
RACKETS	MAXBOLT RACKET GALLANT FORCE BLACK
RACKETS	MAXBOLT RACKET SUPERSTAR 10
RACKETS	MAXBOLT RALLY
RACKETS	MAXBOLT RAPTOR 9
RACKETS	MAXBOLT RAPTOR X 7 / HH
RACKETS	MAXBOLT SPADE / HH
RACKETS	MAXBOLT SUPERSTAR 11
RACKETS	MAXBOLT SUPERSTAR ACE
RACKETS	MAXBOLT SUPERSTAR LT / HH
RACKETS	MAXBOLT SUPERSTAR NOVA
RACKETS	MAXBOLT SUPERSTAR SWIFT
RACKETS	MAXBOLT SUPREME DNA / HH
RACKETS	MAXBOLT SWORD 3 / EB
RACKETS	MAXBOLT THUNDER BOLT / EB
RACKETS	MAXBOLT TRAINING RACKET 120G
RACKETS	MAXBOLT WOVEN TEC 60 / EB
RACKETS	MAXBOLT WOVEN TEC 90
RACKETS	VICTOR AURA SPEED
RACKETS	VICTOR IRON MAN
RACKETS	VICTOR THRUSTER RYUGA
RACKETS	WISH RACKET CLASSICAL 216 BEGINNER
RACKETS	WISH RACKET CLASSICAL 316/317 / BEGINNER
RACKETS	YONEX ARCSABER  LIGHT / EB
RACKETS	YONEX ARCSABER 11 PLAY
RACKETS	YONEX ARCSABER 11 PRO
RACKETS	YONEX ARCSABER 7 PLAY / EB
RACKETS	YONEX ARCSABER 7 PRO
RACKETS	YONEX ASTROX 0.7DG
RACKETS	YONEX ASTROX 100 GAME
RACKETS	YONEX ASTROX 100ZZ 4U / HH
RACKETS	YONEX ASTROX 1DG / HH
RACKETS	YONEX ASTROX 22 F
RACKETS	YONEX ASTROX 22 LT
RACKETS	YONEX ASTROX 27I / 21I/ 43I/ 37I /45I LITE / HH
RACKETS	YONEX ASTROX 3DG / HH
RACKETS	YONEX ASTROX 77 PLAY
RACKETS	YONEX ASTROX 77 PRO (4U) HH
RACKETS	YONEX ASTROX 77 TOUR
RACKETS	YONEX ASTROX 7DG / HH
RACKETS	YONEX ASTROX 88 PLAY / HH
RACKETS	YONEX ASTROX 88D GAME / HH
RACKETS	YONEX ASTROX 88D PRO / HH
RACKETS	YONEX ASTROX 88S PRO
RACKETS	YONEX ASTROX 99 GAME
RACKETS	YONEX ASTROX 99 play / HH
RACKETS	YONEX ASTROX 99 PRO / HH
RACKETS	YONEX ASTROX 99 TOUR
RACKETS	YONEX ASTROX ATTACK 9
RACKETS	YONEX ASTROX LITE 27i
RACKETS	YONEX ASTROX LITE 37i
RACKETS	YONEX ASTROX LITE 43i
RACKETS	YONEX ASTROX LITE 45i
RACKETS	YONEX ASTROX NEXTAGE
RACKETS	YONEX ASTROX SMASH / HH
RACKETS	YONEX DUORA Z STRIKE
RACKETS	YONEX GR 303
RACKETS	YONEX NANOFLARE 1000 GAME
RACKETS	YONEX NANOFLARE 1000 PLAY
RACKETS	YONEX NANOFLARE 1000 ZZ
RACKETS	YONEX NANOFLARE 700
RACKETS	YONEX NANOFLARE 700 PLAY
RACKETS	YONEX NANOFLARE 700 PRO
RACKETS	YONEX NANOFLARE 800 play
RACKETS	YONEX NANOFLARE 800 PRO
RACKETS	YONEX NANOFLARE NEXTAGE
RACKETS	YONEX NANORAY  LIte / HL
RACKETS	YONEX NANORAY 20
RACKETS	YONEX NANORAY 9 / ACE
RACKETS	YONEX VOLTRIC  LITE 40i
RACKETS	YONEX VOLTRIC LITE 20I/25I/35i/37i/40i/47i / HH
RACKETS	YONEX VOLTRIC LITE 35i
RACKETS	YONEX VOLTRIC LITE 47i
RACKETS	YOUNG GT / ENERGY
RACKETS	APACS COMMANDER 80
RACKETS	APACS RACKET
RACKETS	APACS SATELLITE
RACKETS	FELET TJ 1000
RACKETS	FLEX RACKETS
RACKETS	GONGKE K1/K3/K5
RACKETS	HNDRD MEDAL MASTER
RACKETS	HUNDRED BATTLE 900
RACKETS	HUNDRED CULT 77
RACKETS	HUNDRED CULT 79
RACKETS	HUNDRED CULT 82
RACKETS	HUNDRED FLUTTER FF ZOOM/ATTK
RACKETS	HUNDRED GLORY
RACKETS	HUNDRED PREDATOR 79
RACKETS	HUNDRED PREDATOR 82
RACKETS	HUNDRED PRIMEARMOUR RACKET
RACKETS	HUNDRED VIPER ATTK RACKET
RACKETS	LI -NING COMBAT-Z8
RACKETS	LI NING 3D BREAKFREE 90 TD
RACKETS	LI NING 3D CALIBER 300COMBAT
RACKETS	LI NING 3D CALIBER 600 COMBAT
RACKETS	LI NING 3D CALIBER 900 COMBAT
RACKETS	LI NING AERONAUT 9000 D
RACKETS	LI NING AIR FORCE
RACKETS	LI NING AIR FORCE 77 G3
RACKETS	LI NING AIR FORCE 78 G2
RACKETS	LI NING AIR FORCE 79 G4
RACKETS	LI NING BLADE X
RACKETS	LI NING BLAZE 100
RACKETS	LI NING CHALLENGER 15 BOOST
RACKETS	LI NING G FORCE 120/150 / EB
RACKETS	LI NING G FORCE LITE 3000
RACKETS	LI NING G FORCE SUPERLITE
RACKETS	LI NING G-TEK
RACKETS	LI NING IGNITE 7
RACKETS	LI NING JUNIOR RACKET
RACKETS	LI NING SUPER FORCE 84
RACKETS	LI NING SUPER SERIES 100
RACKETS	LI NING TURBO CHARGING 40 (WHITE)
RACKETS	LI NING TURBO CHARGING 50
RACKETS	LI NING TURBO CHARGING 50 DRIVE
RACKETS	LI NING TURBO CHARGING Z
RACKETS	LI NING TURBO X G5
RACKETS	MAXBOLT GALLENT SAKIKO WHITE
RACKETS	MAXBOLT RACKET GALLANT FORCE BLUE
RACKETS	MAXBOLT RACKET PREDATOR BLACK
RACKETS	MAXBOLT RACKET PREDATOR WHITE
RACKETS	MAXBOLT RACKET SUPERSTAR WHITE
RACKETS	MAXBOLT WOVEN TECH 60 - PINK
RACKETS	POWERMAX
RACKETS	SUPER SERIES 900/800 / HH
RACKETS	TURBO CHARGE N9II
RACKETS	YONEX ASTROX 10 DG
RACKETS	YONEX GR 202
RACKETS	YONEX MUSCLE POWER 55
SHOES	HUNDRED COURT FLYER UK-1 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-2 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-2 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-9 GREEN/DARK GREY
SHOES	HUNDRED RAZE UK-7 BLUE/GREEN
SHOES	LI NING SAGA LITE 3 EUR-42 BLACK\BLUE
SHOES	FULL GEL PAD
SHOES	GRAFTEC SHOE
SHOES	HALF GEL PAD
SHOES	HUNDRED BLADE LITE
SHOES	HUNDRED BLADE PRO
SHOES	HUNDRED BLADE SHOE
SHOES	HUNDRED COURT FLYER UK-1 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-10 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-10 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-11 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-11 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-2 BLACK\BLUE
SHOES	HUNDRED COURT FLYER UK-3 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-5 BLACK\BLUE
SHOES	HUNDRED COURT FLYER UK-5 BLACK\LIME
SHOES	HUNDRED COURT FLYER UK-5 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-5 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-6 BLACK\BLUE
SHOES	HUNDRED COURT FLYER UK-6 BLACK\LIME
SHOES	HUNDRED COURT FLYER UK-6 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-6 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-7 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-8 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-9 BLUE/ORANGE
SHOES	HUNDRED COURT STAR PRO UK-1 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-2 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-3 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-4 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-5 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-6 WHITE/PINK
SHOES	HUNDRED COURT ZOOM UK-8 BLUE/GREEN
SHOES	HUNDRED COURT ZOOM UK-9 BLUE/LIME
SHOES	HUNDRED COURTACE KIDS
SHOES	HUNDRED INFINITY
SHOES	HUNDRED RAZE PRO UK-1 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-10 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-11 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-2 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-2 BLUE
SHOES	HUNDRED RAZE PRO UK-3 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-4 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-6 BLACK/BLUE
SHOES	HUNDRED RAZE PRO UK-6 BLACK/ORANGE
SHOES	HUNDRED RAZE UK-1 RED
SHOES	HUNDRED RAZE UK-1 WHITE
SHOES	HUNDRED RAZE UK-10 BLUE/GREEN
SHOES	HUNDRED RAZE UK-2 BLACK
SHOES	HUNDRED RAZE UK-2 BLUE
SHOES	HUNDRED RAZE UK-2 BLUE/GREEN
SHOES	HUNDRED RAZE UK-2 RED
SHOES	HUNDRED RAZE UK-2 WHITE
SHOES	HUNDRED RAZE UK-3 BLUE
SHOES	HUNDRED RAZE UK-3 BLUE/GREEN
SHOES	HUNDRED RAZE UK-3 RED
SHOES	HUNDRED RAZE UK-4 BLUE
SHOES	HUNDRED RAZE UK-4 BLUE/GREEN
SHOES	HUNDRED RAZE UK-4 WHITE
SHOES	HUNDRED RAZE UK-5 BLACK
SHOES	HUNDRED RAZE UK-5 WHITE
SHOES	HUNDRED RAZE UK-6 BLUE/GREEN
SHOES	HUNDRED RAZE UK-6 RED
SHOES	HUNDRED RAZE UK-7 RED
SHOES	HUNDRED RAZE UK-8 BLACK
SHOES	HUNDRED RAZE UK-8 BLUE
SHOES	HUNDRED RAZE UK-9 BLUE
SHOES	HUNDRED RAZE UK-9 BLUE
SHOES	HUNDRED RAZE UK-9 BLUE/GREEN
SHOES	HUNDRED RAZE UK-9 RED
SHOES	HUNDRED RAZE UK-9 YELLOW
SHOES	HUNDRED SHEILD
SHOES	KONNEX EUR-30 BLUE
SHOES	KONNEX EUR-30 MIDNIGHT BLUE
SHOES	LI NING ALMIGHTY V
SHOES	LI NING ALMIGHTY V UK-10 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-5 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-6 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-7 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-8 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-9 LIGHT BLUE
SHOES	LI NING BLAST LITE
SHOES	LI NING DF LITE
SHOES	LI NING DF LITE EUR-6
SHOES	LI NING DF LITE EUR-7
SHOES	LI NING DF LITE EUR-8
SHOES	LI NING DF LITE EUR-9
SHOES	LI NING DF LITE UK-5 RED/WHITE
SHOES	LI NING DF LITE UK-6 BLUE/NEON
SHOES	LI NING DF LITE UK-7 RED/WHITE
SHOES	LI NING DF LITE UK-7.5 BLACK/WHITE
SHOES	LI NING DF LITE UK-8 RED/WHITE
SHOES	LI NING DF LITE UK-9 BLACK/WHITE
SHOES	LI NING DF PRO
SHOES	Li Ning Energy 10
SHOES	LI NING ERUPT SHOE
SHOES	LI NING FLY
SHOES	LI NING HALBERD III SHOE
SHOES	LI NING HYPERSONIC SHOE
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-
SHOES	LI NING HYPERSONIC UK-7 BLUE/LIME
SHOES	LI NING JF-1 SE
SHOES	LI NING LT LITE
SHOES	LI NING MIRAGE PRO
SHOES	LI NING MIRAGE SE
SHOES	LI NING SAGA LITE 8
SHOES	LI NING SAGA TF 02
SHOES	LI NING THUNDER JR
SHOES	LI NING ULTRA FLY 2
SHOES	LI NING ULTRA FLY 3
SHOES	NIVIA EUR-32 RED
SHOES	NIVIA HY-COURT SHOE
SHOES	NIVIA/KONNEX (KIDS)
SHOES	PUKS DRIVE X EUR-32 BLACK\YELLOW
SHOES	PUKS DRIVE X EUR-32 BLUE\CYAN
SHOES	PUKS DRIVE X EUR-33 BLUE\CYAN
SHOES	PUKS DRIVE X EUR-33 RED\WHITE
SHOES	PUKS DRIVE X EUR-34 BLUE\CYAN
SHOES	PUKS DRIVE X EUR-34 RED
SHOES	PUKS DRIVE X UK-1 RED
SHOES	PUKS DRIVE X UK-10 DARK BLUE
SHOES	PUKS DRIVE X UK-10 RED
SHOES	PUKS DRIVE X UK-10 WHITE\GOLD
SHOES	PUKS DRIVE X UK-11 DARK BLUE
SHOES	PUKS DRIVE X UK-11 WHITE\GOLD
SHOES	PUKS DRIVE X UK-2 DARK BLUE
SHOES	PUKS DRIVE X UK-2 RED
SHOES	PUKS DRIVE X UK-3 DARK BLUE
SHOES	PUKS DRIVE X UK-3 LIGHT BLUE
SHOES	PUKS DRIVE X UK-3 RED
SHOES	PUKS DRIVE X UK-4 LIGHT BLUE
SHOES	PUKS DRIVE X UK-4 RED
SHOES	PUKS DRIVE X UK-5 LIGHT BLUE
SHOES	PUKS DRIVE X UK-5 RED
SHOES	PUKS DRIVE X UK-6 DARK BLUE
SHOES	PUKS DRIVE X UK-6 RED
SHOES	PUKS DRIVE X UK-7 DARK BLUE
SHOES	PUKS DRIVE X UK-7 RED
SHOES	PUKS DRIVE X UK-8 DARK BLUE
SHOES	PUKS DRIVE X UK-8 LIGHT BLUE
SHOES	PUKS DRIVE X UK-8 RED
SHOES	PUKS DRIVE X UK-9 DARK BLUE
SHOES	PUKS DRIVE X UK-9 LIGHT BLUE
SHOES	PUKS DRIVE X UK-9 RED
SHOES	PUKS DRIVE X UK-9 WHITE\GOLD
SHOES	PUKS GLADIATOR BADMINTON SHOE
SHOES	VECTOR SHOES
SHOES	VECTOR SUPERNOVA
SHOES	YONEX  DRIVE I UK-10 BLUE
SHOES	YONEX AERUS Z
SHOES	YONEX BLAZE 2 I
SHOES	YONEX BLAZE III
SHOES	YONEX CASCADE DRIVE
SHOES	YONEX CASCADE DRIVE 2
SHOES	YONEX COMFORT Z UK-10 WHITE/GREEN
SHOES	YONEX DIAL 88
SHOES	YONEX DOMINANT 2
SHOES	YONEX DUAL SHOES
SHOES	YONEX ECLIPTION Z
SHOES	YONEX INFINITY 2
SHOES	YONEX SHB 37 UK-1 WHITE
SHOES	YONEX SHB 37 UK-2 WHITE
SHOES	YONEX SHB 37 UK-8 YELLOW
SHOES	YONEX SHB 39 UK-1 BLUE
SHOES	YONEX SHB 39 UK-2 BLUE
SHOES	YONEX SHB 39 UK-3 BLUE
SHOES	YONEX SHB 39 UK-8 BLUE/ORANGE
SHOES	YONEX SHB 39 UK-8 WHITE\ORANGE
SHOES	YONEX SHB 50
SHOES	YONEX SHB 57 (BLACK/RED)
SHOES	YONEX SHB 65 Z WHITE TIGER
SHOES	YONEX SHB 65 Z3 UK-10 WHITE/BLUE
SHOES	YONEX SKILL TOUR
SHOES	YONEX STRIDER BEAT
SHOES	YONEX STRIDER BEAT UK-5 PINK
SHOES	YONEX STRIDER BEAT UK-6 WHITE
SHOES	YONEX STRIDER BEAT UK-8 PINK
SHOES	YONEX VELO 100 UK-1 BLACK
SHOES	YONEX VELO 100 UK-1 BLUE
SHOES	YONEX VELO 100 UK-1 GRAY/LIME
SHOES	YONEX VELO 100 UK-11 BLUE
SHOES	YONEX VELO 100 UK-11 RED
SHOES	YONEX VELO 100 UK-2 BLACK
SHOES	YONEX VELO 100 UK-2 BLUE
SHOES	YONEX VELO 100 UK-2 RED
SHOES	YONEX VELO 100 UK-3 BLACK
SHOES	YONEX VELO 100 UK-3 BLACK
SHOES	YONEX VELO 100 UK-3 RED
SHOES	YONEX VELO 100 UK-4 BLACK
SHOES	YONEX VELO 100 UK-4 BLUE
SHOES	YONEX VELO 100 UK-4 RED
SHOES	YONEX VELO 100 UK-5 WHITE
SHOES	YONEX VELO 100 UK-7 BLACK
SHOES	YONEX VELO 100 UK-7 BLUE
SHOES	YONEX VELO 100 UK-8 BLACK
SHOES	YONEX VELO 100 UK-8 BLUE
SHOES	YONEX VELO 100 UK-8 RED
SHOES	YONEX VELO 100 UK-9 BLACK
SHOES	YONEX VELO 100 UK-9 WHITE
SHOES	HUNDRED RAZE PRO
SHOES	ADIDAS SHOE
SHOES	asics cricket shoe
SHOES	HUNDRED COURT STAR PRO
SHOES	HUNDRED RAZE SHOE
SHOES	LI NING  AYTT019
SHOES	LI NING CLOUD ACE III (New)
SHOES	LI NING LIGHT FEATHER
SHOES	LI NING RANGER LITE Z1
SHOES	LI NING SURURTRISE ATTACK
SHOES	LI NING ULTRA  IV
SHOES	LI NING ULTRA III JUNIOR
SHOES	LI NING ULTRA POWER
SHOES	PUKS DRIVE X BADMINTON SHOE
SHOES	SHOES  ASICS (BLAST FF 3)
SHOES	ULTRA FORCE
SHOES	ULTRA SPEED
SHOES	VICTOR SHOES
SHOES	VICTOT LS.S SHOE
SHOES	YONEX SHB 37
SHOES	YONEX SHB 39
SHOES	YONEX SKILL
SHOES	YONEX VELO 100
SHUTTLECOCKS	LI NING C 60
SHUTTLECOCKS	LIN MEI 10
SHUTTLECOCKS	HUNDRED F8
SHUTTLECOCKS	LI MEI 10 PRO
SHUTTLECOCKS	LI NING A2
SHUTTLECOCKS	LI NING D3
SHUTTLECOCKS	LI NING G800
SHUTTLECOCKS	LI NING SG GOLD
SHUTTLECOCKS	LIN MEI F7
SHUTTLECOCKS	LIN MEI G3
SHUTTLECOCKS	MAVIS 600
SHUTTLECOCKS	MAVIS 600 SINGLES
SHUTTLECOCKS	VONEX TUBE
SHUTTLECOCKS	VONEX TUBE SINGLE
SHUTTLECOCKS	MAVIS 600 (BLUE)
SHUTTLECOCKS	RSL
SOCKS	HUNDRED 3 PACK SOCKS
SOCKS	HUNDRED SOCKS
SOCKS	LI NING 3 PACK SOCKS
SOCKS	LI NING SOCKS
SOCKS	LI NING SOCKS (AWLS)
SOCKS	LI NING SOCKS (AWST)
SOCKS	MAXBOLT JUNIOR SOCKS
SOCKS	MAXBOLT SOCKS
SOCKS	YONEX 3 PACK SOCKS
SOCKS	YONEX SOCKS
SOCKS	YONEX SOCKS (CH)
STRINGS	APACS STRINGS
STRINGS	GOSEN RY 58/65
STRINGS	GOSEN RY 65/58 SINGLE
STRINGS	HUNDRED 700S/600S
STRINGS	HUNDRED HYBRID
STRINGS	HUNDRED JP 70
STRINGS	HUNDRED Z70 STRINGS
STRINGS	HUNRED 66X BOOST
STRINGS	HUNRED 70X BOOST
STRINGS	KELIST 99/98/66 PRO
STRINGS	KELIST K618
STRINGS	KONEX STRINGS
STRINGS	LI NING AP 66
STRINGS	LI NING AP 70
STRINGS	LI NING L 67
STRINGS	LI NING N 65
STRINGS	LI NING N 65 SINGLE
STRINGS	LI NING N 70
STRINGS	LI NING N 70 SINGLE
STRINGS	LI NING N9
STRINGS	LI NING NO 1
STRINGS	LI NING NO 1 BOOST
STRINGS	LI NING NO 3 BOOST
STRINGS	LI NING NO 5
STRINGS	LI NING NO 5 SINGLE
STRINGS	LI NING NO 7 BOOST
STRINGS	LI NING NO 7 REEL
STRINGS	LI NING NS 50
STRINGS	LI NING NS 95
STRINGS	MAXBOLT ARC-Z66
STRINGS	MAXBOLT MBS 20
STRINGS	MAXBOLT MBS 6
STRINGS	MAXBOLT MBS 6+
STRINGS	MAXBOLT MBS 63
STRINGS	MAXBOLT MBS 66 BLACK
STRINGS	MAXBOLT MBS 66 RED
STRINGS	MAXBOLT MBS 66 TWO TONE (RED/BLACK)
STRINGS	MAXBOLT MBS 66 WHITE
STRINGS	MAXBOLT MBS 66 YELLOW
STRINGS	MAXBOLT MBS 70
STRINGS	MAXBOLT STRING MBS 66
STRINGS	MAXBOLT STRING MBS 90
STRINGS	T20 STRING
STRINGS	TRANSFORMER TS 101 PRO
STRINGS	VICTOR VB 70 / 70 POWER
STRINGS	VICTOR VS-65
STRINGS	YONEX AEROBITE
STRINGS	YONEX AEROBITE BOOST
STRINGS	YONEX AEROSONIC
STRINGS	YONEX BG 65 BLACK
STRINGS	YONEX BG 65 GOLD
STRINGS	YONEX BG 65 GREEN
STRINGS	YONEX BG 65 LAVENDER
STRINGS	YONEX BG 65 ORANGE
STRINGS	YONEX BG 65 PINK
STRINGS	YONEX BG 65 RED
STRINGS	YONEX BG 65 REEL N
STRINGS	YONEX BG 65 ROYAL BLUE
STRINGS	YONEX BG 65 SINGLE
STRINGS	YONEX BG 65 TITANIUM
STRINGS	YONEX BG 65 TITANIUM SINGLE
STRINGS	YONEX BG 65 TURQUOISE
STRINGS	YONEX BG 65 VIOLET
STRINGS	YONEX BG 65 WHITE
STRINGS	YONEX BG 65 YELLOW
STRINGS	YONEX BG 66 ULTIMAX BLACK
STRINGS	YONEX BG 66 ULTIMAX METTALIC WHITE
STRINGS	YONEX BG 66 ULTIMAX PASTAL GREEN
STRINGS	YONEX BG 66 ULTIMAX RED
STRINGS	YONEX BG 66 ULTIMAX REEL
STRINGS	YONEX BG 66 ULTIMAX SINGLE
STRINGS	YONEX BG 66 ULTIMAX YELLOW
STRINGS	YONEX BG 80 POWER
STRINGS	YONEX BG 80 POWER SINGLE
STRINGS	YONEX EXBOLT 63
STRINGS	YONEX EXBOLT 63 REEL
STRINGS	YONEX EXBOLT 65
STRINGS	YONEX EXBOLT 68
STRINGS	YONEX NANOGY 95
STRINGS	YONEX NANOGY 99
STRINGS	APACS PRO 70
STRINGS	YONEX BG 65
STRINGS	YONEX BG 66 ULTIMAX
WRISTBANDS	HUNDRED WRIST BAND
WRISTBANDS	Li Ning WRIST BAND
WRISTBANDS	YONEX WRIST BAND
WRISTBANDS	GR 2 WRISTBAND`;

// Generate SKU
function generateSKU(category, index) {
  const categoryAbbrev = {
    'GRIPS': 'GRP',
    'STRINGS': 'STR',
    'SOCKS': 'SOK',
    'SHUTTLECOCKS': 'SHU',
    'RACKETS': 'RAC',
    'WRISTBANDS': 'WRS',
    'OTHER': 'OTH',
    'NETS': 'NET',
    'SHOES': 'SHO',
    'BAGS': 'BAG',
    'CLOTHS': 'CLO'
  };
  
  const abbrev = categoryAbbrev[category] || 'OTH';
  const paddedIndex = String(index).padStart(4, '0');
  return `${abbrev}${paddedIndex}`;
}

// Parse product data
function parseProductData(data) {
  const lines = data.trim().split('\n');
  const products = [];
  
  for (const line of lines) {
    if (!line.trim()) continue;
    
    const parts = line.split('\t');
    if (parts.length < 2) continue;
    
    const category = parts[0].trim();
    const name = parts[1].trim();
    
    products.push({
      category,
      name: name.replace(/'/g, "'").replace(/"/g, '"') // Clean quotes
    });
  }
  
  return products;
}

async function addRemainingProducts() {
  try {
    console.log('🚀 Starting to add remaining products from complete dataset...');
    
    // Get existing products to avoid duplicates
    const existingProducts = await prisma.product.findMany({
      select: { name: true }
    });
    const existingNames = new Set(existingProducts.map(p => p.name));
    console.log(`📋 Found ${existingNames.size} existing products to check against`);
    
    // Get categories and shops
    const categories = await prisma.category.findMany();
    const shops = await prisma.shop.findMany();
    const defaultShopId = shops[0]?.id;
    
    if (!defaultShopId) {
      throw new Error('No shops found!');
    }
    
    // Parse all products
    const allProducts = parseProductData(completeProductData);
    console.log(`📦 Parsed ${allProducts.length} products from complete dataset`);
    
    // Filter out duplicates
    const uniqueProducts = allProducts.filter(p => !existingNames.has(p.name));
    console.log(`✨ Found ${uniqueProducts.length} NEW products to add`);
    console.log(`⏭️  Skipping ${allProducts.length - uniqueProducts.length} existing products`);
    
    if (uniqueProducts.length === 0) {
      console.log('🎉 All products are already in the database!');
      return;
    }
    
    // Group by category
    const productsByCategory = {};
    for (const product of uniqueProducts) {
      if (!productsByCategory[product.category]) {
        productsByCategory[product.category] = [];
      }
      productsByCategory[product.category].push(product);
    }
    
    // Show what we'll be adding
    console.log('\n📊 New products by category:');
    for (const [cat, prods] of Object.entries(productsByCategory)) {
      console.log(`  ${cat}: ${prods.length} new products`);
    }
    
    let totalInserted = 0;
    const categoryCounter = { ...currentCounts };
    
    // Process each category
    for (const [categoryName, products] of Object.entries(productsByCategory)) {
      console.log(`\n📁 Processing ${categoryName}: ${products.length} products`);
      
      const category = categories.find(c => c.name === categoryName);
      if (!category) {
        console.log(`⚠️  Category ${categoryName} not found, skipping...`);
        continue;
      }
      
      for (let i = 0; i < products.length; i++) {
        const product = products[i];
        const currentCount = categoryCounter[categoryName] + i + 1;
        const sku = generateSKU(categoryName, currentCount);
        
        try {
          await prisma.product.create({
            data: {
              name: product.name,
              sku: sku,
              price: 0,
              category: { connect: { id: category.id } },
              shop: { connect: { id: defaultShopId } }
            }
          });
          
          console.log(`✅ ${sku}: ${product.name}`);
          totalInserted++;
          
        } catch (error) {
          if (error.code === 'P2002') {
            console.log(`⚠️  Duplicate: ${product.name}`);
          } else {
            console.log(`❌ Failed: ${product.name} - ${error.message}`);
          }
        }
      }
      
      categoryCounter[categoryName] += products.length;
    }
    
    console.log(`\n🎉 Successfully added ${totalInserted} NEW products!`);
    console.log('\n📊 Updated category counts:');
    console.log(categoryCounter);
    
    const newTotal = Object.values(categoryCounter).reduce((sum, count) => sum + count, 0);
    console.log(`\n📈 Total products in database: ${newTotal}`);
    
  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await prisma.$disconnect();
  }
}

addRemainingProducts(); 