const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

// Updated counts after batch 2
const currentCounts = {
  'BAGS': 86,
  'CLOTHS': 30,
  'GRIPS': 25,
  'NETS': 7,
  'OTHER': 36,
  'RACKETS': 227,
  'SHOES': 133,
  'SHUTTLECOCKS': 8,
  'SOCKS': 7,
  'STRINGS': 61,
  'WRISTBANDS': 2
};

// Batch 3: Final categories (SHOES, SHUTTLECOCKS, SOCKS, STRINGS, WRISTBANDS)
const batch3Dataset = `SHOES	HUNDRED COURT FLYER UK-1 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-2 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-2 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-9 GREEN/DARK GREY
SHOES	HUNDRED RAZE UK-7 BLUE/GREEN
SHOES	LI NING SAGA LITE 3 EUR-42 BLACK\BLUE
SHOES	FULL GEL PAD
SHOES	GRAFTEC SHOE
SHOES	HALF GEL PAD
SHOES	HUNDRED BLADE LITE
SHOES	HUNDRED BLADE PRO
SHOES	HUNDRED BLADE SHOE
SHOES	HUNDRED COURT FLYER UK-1 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-10 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-10 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-11 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-11 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-2 BLACK\BLUE
SHOES	HUNDRED COURT FLYER UK-3 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-5 BLACK\BLUE
SHOES	HUNDRED COURT FLYER UK-5 BLACK\LIME
SHOES	HUNDRED COURT FLYER UK-5 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-5 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-6 BLACK\BLUE
SHOES	HUNDRED COURT FLYER UK-6 BLACK\LIME
SHOES	HUNDRED COURT FLYER UK-6 BLUE/ORANGE
SHOES	HUNDRED COURT FLYER UK-6 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-7 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-8 GREEN/DARK GREY
SHOES	HUNDRED COURT FLYER UK-9 BLUE/ORANGE
SHOES	HUNDRED COURT STAR PRO UK-1 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-2 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-3 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-4 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-5 BLUE/RED
SHOES	HUNDRED COURT STAR PRO UK-6 WHITE/PINK
SHOES	HUNDRED COURT ZOOM UK-8 BLUE/GREEN
SHOES	HUNDRED COURT ZOOM UK-9 BLUE/LIME
SHOES	HUNDRED COURTACE KIDS
SHOES	HUNDRED INFINITY
SHOES	HUNDRED RAZE PRO UK-1 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-10 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-11 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-2 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-2 BLUE
SHOES	HUNDRED RAZE PRO UK-3 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-4 BLACK/ORANGE
SHOES	HUNDRED RAZE PRO UK-6 BLACK/BLUE
SHOES	HUNDRED RAZE PRO UK-6 BLACK/ORANGE
SHOES	HUNDRED RAZE UK-1 RED
SHOES	HUNDRED RAZE UK-1 WHITE
SHOES	HUNDRED RAZE UK-10 BLUE/GREEN
SHOES	HUNDRED RAZE UK-2 BLACK
SHOES	HUNDRED RAZE UK-2 BLUE
SHOES	HUNDRED RAZE UK-2 BLUE/GREEN
SHOES	HUNDRED RAZE UK-2 RED
SHOES	HUNDRED RAZE UK-2 WHITE
SHOES	HUNDRED RAZE UK-3 BLUE
SHOES	HUNDRED RAZE UK-3 BLUE/GREEN
SHOES	HUNDRED RAZE UK-3 RED
SHOES	HUNDRED RAZE UK-4 BLUE
SHOES	HUNDRED RAZE UK-4 BLUE/GREEN
SHOES	HUNDRED RAZE UK-4 WHITE
SHOES	HUNDRED RAZE UK-5 BLACK
SHOES	HUNDRED RAZE UK-5 WHITE
SHOES	HUNDRED RAZE UK-6 BLUE/GREEN
SHOES	HUNDRED RAZE UK-6 RED
SHOES	HUNDRED RAZE UK-7 RED
SHOES	HUNDRED RAZE UK-8 BLACK
SHOES	HUNDRED RAZE UK-8 BLUE
SHOES	HUNDRED RAZE UK-9 BLUE
SHOES	HUNDRED RAZE UK-9 BLUE
SHOES	HUNDRED RAZE UK-9 BLUE/GREEN
SHOES	HUNDRED RAZE UK-9 RED
SHOES	HUNDRED RAZE UK-9 YELLOW
SHOES	HUNDRED SHEILD
SHOES	KONNEX EUR-30 BLUE
SHOES	KONNEX EUR-30 MIDNIGHT BLUE
SHOES	LI NING ALMIGHTY V
SHOES	LI NING ALMIGHTY V UK-10 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-5 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-6 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-7 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-8 LIGHT BLUE
SHOES	LI NING ALMIGHTY V UK-9 LIGHT BLUE
SHOES	LI NING BLAST LITE
SHOES	LI NING DF LITE
SHOES	LI NING DF LITE EUR-6
SHOES	LI NING DF LITE EUR-7
SHOES	LI NING DF LITE EUR-8
SHOES	LI NING DF LITE EUR-9
SHOES	LI NING DF LITE UK-5 RED/WHITE
SHOES	LI NING DF LITE UK-6 BLUE/NEON
SHOES	LI NING DF LITE UK-7 RED/WHITE
SHOES	LI NING DF LITE UK-7.5 BLACK/WHITE
SHOES	LI NING DF LITE UK-8 RED/WHITE
SHOES	LI NING DF LITE UK-9 BLACK/WHITE
SHOES	LI NING DF PRO
SHOES	Li Ning Energy 10
SHOES	LI NING ERUPT SHOE
SHOES	LI NING FLY
SHOES	LI NING HALBERD III SHOE
SHOES	LI NING HYPERSONIC SHOE
SHOES	LI NING HYPERSONIC UK-7 BLUE/LIME
SHOES	LI NING JF-1 SE
SHOES	LI NING LT LITE
SHOES	LI NING MIRAGE PRO
SHOES	LI NING MIRAGE SE
SHOES	LI NING SAGA LITE 8
SHOES	LI NING SAGA TF 02
SHOES	LI NING THUNDER JR
SHOES	LI NING ULTRA FLY 2
SHOES	LI NING ULTRA FLY 3
SHOES	NIVIA EUR-32 RED
SHOES	NIVIA HY-COURT SHOE
SHOES	NIVIA/KONNEX (KIDS)
SHOES	PUKS DRIVE X EUR-32 BLACK\YELLOW
SHOES	PUKS DRIVE X EUR-32 BLUE\CYAN
SHOES	PUKS DRIVE X EUR-33 BLUE\CYAN
SHOES	PUKS DRIVE X EUR-33 RED\WHITE
SHOES	PUKS DRIVE X EUR-34 BLUE\CYAN
SHOES	PUKS DRIVE X EUR-34 RED
SHOES	PUKS DRIVE X UK-1 RED
SHOES	PUKS DRIVE X UK-10 DARK BLUE
SHOES	PUKS DRIVE X UK-10 RED
SHOES	PUKS DRIVE X UK-10 WHITE\GOLD
SHOES	PUKS DRIVE X UK-11 DARK BLUE
SHOES	PUKS DRIVE X UK-11 WHITE\GOLD
SHOES	PUKS DRIVE X UK-2 DARK BLUE
SHOES	PUKS DRIVE X UK-2 RED
SHOES	PUKS DRIVE X UK-3 DARK BLUE
SHOES	PUKS DRIVE X UK-3 LIGHT BLUE
SHOES	PUKS DRIVE X UK-3 RED
SHOES	PUKS DRIVE X UK-4 LIGHT BLUE
SHOES	PUKS DRIVE X UK-4 RED
SHOES	PUKS DRIVE X UK-5 LIGHT BLUE
SHOES	PUKS DRIVE X UK-5 RED
SHOES	PUKS DRIVE X UK-6 DARK BLUE
SHOES	PUKS DRIVE X UK-6 RED
SHOES	PUKS DRIVE X UK-7 DARK BLUE
SHOES	PUKS DRIVE X UK-7 RED
SHOES	PUKS DRIVE X UK-8 DARK BLUE
SHOES	PUKS DRIVE X UK-8 LIGHT BLUE
SHOES	PUKS DRIVE X UK-8 RED
SHOES	PUKS DRIVE X UK-9 DARK BLUE
SHOES	PUKS DRIVE X UK-9 LIGHT BLUE
SHOES	PUKS DRIVE X UK-9 RED
SHOES	PUKS DRIVE X UK-9 WHITE\GOLD
SHOES	PUKS GLADIATOR BADMINTON SHOE
SHOES	VECTOR SHOES
SHOES	VECTOR SUPERNOVA
SHOES	YONEX  DRIVE I UK-10 BLUE
SHOES	YONEX AERUS Z
SHOES	YONEX BLAZE 2 I
SHOES	YONEX BLAZE III
SHOES	YONEX CASCADE DRIVE
SHOES	YONEX CASCADE DRIVE 2
SHOES	YONEX COMFORT Z UK-10 WHITE/GREEN
SHOES	YONEX DIAL 88
SHOES	YONEX DOMINANT 2
SHOES	YONEX DUAL SHOES
SHOES	YONEX ECLIPTION Z
SHOES	YONEX INFINITY 2
SHOES	YONEX SHB 37 UK-1 WHITE
SHOES	YONEX SHB 37 UK-2 WHITE
SHOES	YONEX SHB 37 UK-8 YELLOW
SHOES	YONEX SHB 39 UK-1 BLUE
SHOES	YONEX SHB 39 UK-2 BLUE
SHOES	YONEX SHB 39 UK-3 BLUE
SHOES	YONEX SHB 39 UK-8 BLUE/ORANGE
SHOES	YONEX SHB 39 UK-8 WHITE\ORANGE
SHOES	YONEX SHB 50
SHOES	YONEX SHB 57 (BLACK/RED)
SHOES	YONEX SHB 65 Z WHITE TIGER
SHOES	YONEX SHB 65 Z3 UK-10 WHITE/BLUE
SHOES	YONEX SKILL TOUR
SHOES	YONEX STRIDER BEAT
SHOES	YONEX STRIDER BEAT UK-5 PINK
SHOES	YONEX STRIDER BEAT UK-6 WHITE
SHOES	YONEX STRIDER BEAT UK-8 PINK
SHOES	YONEX VELO 100 UK-1 BLACK
SHOES	YONEX VELO 100 UK-1 BLUE
SHOES	YONEX VELO 100 UK-1 GRAY/LIME
SHOES	YONEX VELO 100 UK-11 BLUE
SHOES	YONEX VELO 100 UK-11 RED
SHOES	YONEX VELO 100 UK-2 BLACK
SHOES	YONEX VELO 100 UK-2 BLUE
SHOES	YONEX VELO 100 UK-2 RED
SHOES	YONEX VELO 100 UK-3 BLACK
SHOES	YONEX VELO 100 UK-3 RED
SHOES	YONEX VELO 100 UK-4 BLACK
SHOES	YONEX VELO 100 UK-4 BLUE
SHOES	YONEX VELO 100 UK-4 RED
SHOES	YONEX VELO 100 UK-5 WHITE
SHOES	YONEX VELO 100 UK-7 BLACK
SHOES	YONEX VELO 100 UK-7 BLUE
SHOES	YONEX VELO 100 UK-8 BLACK
SHOES	YONEX VELO 100 UK-8 BLUE
SHOES	YONEX VELO 100 UK-8 RED
SHOES	YONEX VELO 100 UK-9 BLACK
SHOES	YONEX VELO 100 UK-9 WHITE
SHOES	HUNDRED RAZE PRO
SHOES	ADIDAS SHOE
SHOES	asics cricket shoe
SHOES	HUNDRED COURT STAR PRO
SHOES	HUNDRED RAZE SHOE
SHOES	LI NING  AYTT019
SHOES	LI NING CLOUD ACE III (New)
SHOES	LI NING LIGHT FEATHER
SHOES	LI NING RANGER LITE Z1
SHOES	LI NING SURURTRISE ATTACK
SHOES	LI NING ULTRA  IV
SHOES	LI NING ULTRA III JUNIOR
SHOES	LI NING ULTRA POWER
SHOES	PUKS DRIVE X BADMINTON SHOE
SHOES	SHOES  ASICS (BLAST FF 3)
SHOES	ULTRA FORCE
SHOES	ULTRA SPEED
SHOES	VICTOR SHOES
SHOES	VICTOT LS.S SHOE
SHOES	YONEX SHB 37
SHOES	YONEX SHB 39
SHOES	YONEX SKILL
SHOES	YONEX VELO 100
SHUTTLECOCKS	LI NING C 60
SHUTTLECOCKS	LIN MEI 10
SHUTTLECOCKS	HUNDRED F8
SHUTTLECOCKS	LI MEI 10 PRO
SHUTTLECOCKS	LI NING A2
SHUTTLECOCKS	LI NING D3
SHUTTLECOCKS	LI NING G800
SHUTTLECOCKS	LI NING SG GOLD
SHUTTLECOCKS	LIN MEI F7
SHUTTLECOCKS	LIN MEI G3
SHUTTLECOCKS	MAVIS 600
SHUTTLECOCKS	MAVIS 600 SINGLES
SHUTTLECOCKS	VONEX TUBE
SHUTTLECOCKS	VONEX TUBE SINGLE
SHUTTLECOCKS	MAVIS 600 (BLUE)
SHUTTLECOCKS	RSL
SOCKS	HUNDRED 3 PACK SOCKS
SOCKS	HUNDRED SOCKS
SOCKS	LI NING 3 PACK SOCKS
SOCKS	LI NING SOCKS
SOCKS	LI NING SOCKS (AWLS)
SOCKS	LI NING SOCKS (AWST)
SOCKS	MAXBOLT JUNIOR SOCKS
SOCKS	MAXBOLT SOCKS
SOCKS	YONEX 3 PACK SOCKS
SOCKS	YONEX SOCKS
SOCKS	YONEX SOCKS (CH)
STRINGS	APACS STRINGS
STRINGS	GOSEN RY 58/65
STRINGS	GOSEN RY 65/58 SINGLE
STRINGS	HUNDRED 700S/600S
STRINGS	HUNDRED HYBRID
STRINGS	HUNDRED JP 70
STRINGS	HUNDRED Z70 STRINGS
STRINGS	HUNRED 66X BOOST
STRINGS	HUNRED 70X BOOST
STRINGS	KELIST 99/98/66 PRO
STRINGS	KELIST K618
STRINGS	KONEX STRINGS
STRINGS	LI NING AP 66
STRINGS	LI NING AP 70
STRINGS	LI NING L 67
STRINGS	LI NING N 65
STRINGS	LI NING N 65 SINGLE
STRINGS	LI NING N 70
STRINGS	LI NING N 70 SINGLE
STRINGS	LI NING N9
STRINGS	LI NING NO 1
STRINGS	LI NING NO 1 BOOST
STRINGS	LI NING NO 3 BOOST
STRINGS	LI NING NO 5
STRINGS	LI NING NO 5 SINGLE
STRINGS	LI NING NO 7 BOOST
STRINGS	LI NING NO 7 REEL
STRINGS	LI NING NS 50
STRINGS	LI NING NS 95
STRINGS	MAXBOLT ARC-Z66
STRINGS	MAXBOLT MBS 20
STRINGS	MAXBOLT MBS 6
STRINGS	MAXBOLT MBS 6+
STRINGS	MAXBOLT MBS 63
STRINGS	MAXBOLT MBS 66 BLACK
STRINGS	MAXBOLT MBS 66 RED
STRINGS	MAXBOLT MBS 66 TWO TONE (RED/BLACK)
STRINGS	MAXBOLT MBS 66 WHITE
STRINGS	MAXBOLT MBS 66 YELLOW
STRINGS	MAXBOLT MBS 70
STRINGS	MAXBOLT STRING MBS 66
STRINGS	MAXBOLT STRING MBS 90
STRINGS	T20 STRING
STRINGS	TRANSFORMER TS 101 PRO
STRINGS	VICTOR VB 70 / 70 POWER
STRINGS	VICTOR VS-65
STRINGS	YONEX AEROBITE
STRINGS	YONEX AEROBITE BOOST
STRINGS	YONEX AEROSONIC
STRINGS	YONEX BG 65 BLACK
STRINGS	YONEX BG 65 GOLD
STRINGS	YONEX BG 65 GREEN
STRINGS	YONEX BG 65 LAVENDER
STRINGS	YONEX BG 65 ORANGE
STRINGS	YONEX BG 65 PINK
STRINGS	YONEX BG 65 RED
STRINGS	YONEX BG 65 REEL N
STRINGS	YONEX BG 65 ROYAL BLUE
STRINGS	YONEX BG 65 SINGLE
STRINGS	YONEX BG 65 TITANIUM
STRINGS	YONEX BG 65 TITANIUM SINGLE
STRINGS	YONEX BG 65 TURQUOISE
STRINGS	YONEX BG 65 VIOLET
STRINGS	YONEX BG 65 WHITE
STRINGS	YONEX BG 65 YELLOW
STRINGS	YONEX BG 66 ULTIMAX BLACK
STRINGS	YONEX BG 66 ULTIMAX METTALIC WHITE
STRINGS	YONEX BG 66 ULTIMAX PASTAL GREEN
STRINGS	YONEX BG 66 ULTIMAX RED
STRINGS	YONEX BG 66 ULTIMAX REEL
STRINGS	YONEX BG 66 ULTIMAX SINGLE
STRINGS	YONEX BG 66 ULTIMAX YELLOW
STRINGS	YONEX BG 80 POWER
STRINGS	YONEX BG 80 POWER SINGLE
STRINGS	YONEX EXBOLT 63
STRINGS	YONEX EXBOLT 63 REEL
STRINGS	YONEX EXBOLT 65
STRINGS	YONEX EXBOLT 68
STRINGS	YONEX NANOGY 95
STRINGS	YONEX NANOGY 99
STRINGS	APACS PRO 70
STRINGS	YONEX BG 65
STRINGS	YONEX BG 66 ULTIMAX
WRISTBANDS	HUNDRED WRIST BAND
WRISTBANDS	Li Ning WRIST BAND
WRISTBANDS	YONEX WRIST BAND
WRISTBANDS	GR 2 WRISTBAND`;

function generateSKU(category, index) {
  const categoryAbbrev = {
    'GRIPS': 'GRP',
    'STRINGS': 'STR',
    'SOCKS': 'SOK',
    'SHUTTLECOCKS': 'SHU',
    'RACKETS': 'RAC',
    'WRISTBANDS': 'WRS',
    'OTHER': 'OTH',
    'NETS': 'NET',
    'SHOES': 'SHO',
    'BAGS': 'BAG',
    'CLOTHS': 'CLO'
  };
  
  const abbrev = categoryAbbrev[category] || 'OTH';
  const paddedIndex = String(index).padStart(4, '0');
  return `${abbrev}${paddedIndex}`;
}

async function processBatch3() {
  try {
    console.log('🚀 Processing massive product dataset (Final Batch 3)...');
    
    // Get existing products to avoid duplicates
    const existingProducts = await prisma.product.findMany({
      select: { name: true }
    });
    const existingNames = new Set(existingProducts.map(p => p.name));
    console.log(`📋 Found ${existingNames.size} existing products`);
    
    // Get categories and shops
    const categories = await prisma.category.findMany();
    const shops = await prisma.shop.findMany();
    const defaultShopId = shops[0]?.id;
    
    if (!defaultShopId) {
      throw new Error('No shops found!');
    }
    
    // Parse the dataset
    const lines = batch3Dataset.trim().split('\n');
    const allProducts = [];
    
    for (const line of lines) {
      if (!line.trim()) continue;
      
      const parts = line.split('\t');
      if (parts.length < 2) continue;
      
      const category = parts[0].trim();
      const name = parts[1].trim();
      
      allProducts.push({ category, name });
    }
    
    console.log(`📦 Parsed ${allProducts.length} products from final batch dataset`);
    
    // Filter out existing products
    const newProducts = allProducts.filter(p => !existingNames.has(p.name));
    console.log(`✨ Found ${newProducts.length} NEW products to add`);
    console.log(`⏭️  Skipping ${allProducts.length - newProducts.length} existing products`);
    
    if (newProducts.length === 0) {
      console.log('🎉 All products in final batch are already in the database!');
      return;
    }
    
    // Group by category
    const productsByCategory = {};
    for (const product of newProducts) {
      if (!productsByCategory[product.category]) {
        productsByCategory[product.category] = [];
      }
      productsByCategory[product.category].push(product);
    }
    
    // Show what we'll be adding
    console.log('\n📊 New products by category:');
    for (const [cat, prods] of Object.entries(productsByCategory)) {
      console.log(`  ${cat}: ${prods.length} new products`);
    }
    
    let totalProcessed = 0;
    const categoryCounter = { ...currentCounts };
    
    // Process each category
    for (const [categoryName, products] of Object.entries(productsByCategory)) {
      console.log(`\n📁 Processing ${categoryName}: ${products.length} products`);
      
      const category = categories.find(c => c.name === categoryName);
      if (!category) {
        console.log(`⚠️  Category ${categoryName} not found, skipping...`);
        continue;
      }
      
      // Process in smaller batches to avoid connection issues
      const BATCH_SIZE = 25;
      for (let i = 0; i < products.length; i += BATCH_SIZE) {
        const batch = products.slice(i, i + BATCH_SIZE);
        
        for (let j = 0; j < batch.length; j++) {
          const product = batch[j];
          const currentCount = categoryCounter[categoryName] + (i + j) + 1;
          const sku = generateSKU(categoryName, currentCount);
          
          try {
            await prisma.product.create({
              data: {
                name: product.name,
                sku: sku,
                price: 0,
                category: { connect: { id: category.id } },
                shop: { connect: { id: defaultShopId } }
              }
            });
            
            console.log(`✅ ${sku}: ${product.name}`);
            totalProcessed++;
            
          } catch (error) {
            if (error.code === 'P2002') {
              console.log(`⚠️  Duplicate: ${product.name}`);
            } else {
              console.log(`❌ Failed: ${product.name} - ${error.message}`);
            }
          }
        }
        
        // Small delay between batches
        await new Promise(resolve => setTimeout(resolve, 50));
      }
      
      categoryCounter[categoryName] += products.length;
    }
    
    console.log(`\n🎉 Successfully processed ${totalProcessed} NEW products in final batch!`);
    console.log('\n📊 Final category counts:');
    console.log(categoryCounter);
    
    const newTotal = Object.values(categoryCounter).reduce((sum, count) => sum + count, 0);
    console.log(`\n📈 TOTAL PRODUCTS IN DATABASE: ${newTotal}`);
    console.log('\n🏆 COMPLETE! All remaining products from your comprehensive dataset have been processed.');
    
  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await prisma.$disconnect();
  }
}

processBatch3(); 